export const styles = {
    container: {
        maxWidth: "1200px",
        margin: "2rem auto",
    },
    mainCard: {
        boxShadow: "0 10px 25px rgba(0, 0, 0, 0.1)",
        borderRadius: "12px",
        border: "1px solid #e9ecef",
    },
    cardHeader: {
        backgroundColor: "#ffffff",
        borderBottom: "1px solid #e9ecef",
        padding: "1.5rem",
    },
    headerTitle: {
        color: "#333",
        fontWeight: "600",
        fontSize: "1.75rem",
        margin: 0,
        textAlign: "center",
    },
    progressBar: {
        height: "4px",
        backgroundColor: "#e9ecef",
        marginBottom: "2rem",
        marginTop: "1rem",
    },
    progressFill: {
        backgroundColor: "#0d6efd",
        height: "100%",
        transition: "width 0.3s ease",
    },
    stepButton: {
        width: "40px",
        height: "40px",
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        border: "2px solid",
        padding: 0,
        zIndex: 1,
        margin: "0 auto 0.5rem auto",
        fontSize: "0.9rem",
        fontWeight: "600",
        cursor: "pointer",
        background: "none",
    },
    stepButtonActive: {
        backgroundColor: "#0d6efd",
        borderColor: "#0d6efd",
        color: "#fff",
    },
    stepButtonCompleted: {
        backgroundColor: "#fff",
        borderColor: "#0d6efd",
        color: "#0d6efd",
    },
    stepButtonInactive: {
        backgroundColor: "#fff",
        borderColor: "#ced4da",
        color: "#6c757d",
    },
    stepLabel: {
        fontSize: "0.8rem",
        textAlign: "center",
        display: "block",
        marginTop: "0.25rem",
    },
    stepLabelActive: {
        color: "#0d6efd",
        fontWeight: "600",
    },
    stepLabelInactive: {
        color: "#6c757d",
    },
    sectionCard: {
        border: "1px solid #dee2e6",
        borderRadius: "10px",
        boxShadow: "0 4px 6px rgba(0, 0, 0, 0.04)",
        marginBottom: "1.5rem",
    },
    sectionTitle: {
        color: "#333",
        fontWeight: "600",
        marginBottom: "1.5rem",
        fontSize: "1.25rem",
    },
    formLabel: {
        fontWeight: "600",
        color: "#495057",
        marginBottom: "0.5rem",
        display: "block",
    },
    formInput: {
        borderRadius: "6px",
        border: "1px solid #ced4da",
        padding: "0.75rem 1rem",
        fontSize: "1rem",
        width: "100%",
        backgroundColor: "#fff",
    },
    formSelect: {
        borderRadius: "6px",
        border: "1px solid #ced4da",
        padding: "0.75rem 1rem",
        fontSize: "1rem",
        width: "100%",
        backgroundColor: "#fff",
    },
    formTextarea: {
        borderRadius: "6px",
        border: "1px solid #ced4da",
        padding: "0.75rem 1rem",
        fontSize: "1rem",
        width: "100%",
        minHeight: "150px",
        backgroundColor: "#fff",
    },
    formCheckbox: {
        width: "18px",
        height: "18px",
        marginRight: "10px",
    },
    formGroup: {
        marginBottom: "1.5rem",
    },
    button: {
        borderRadius: "6px",
        padding: "0.75rem 1.5rem",
        fontWeight: "500",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
        border: "1px solid transparent",
    },
    primaryButton: {
        backgroundColor: "#0d6efd",
        color: "#fff",
        borderColor: "#0d6efd",
    },
    secondaryButton: {
        backgroundColor: "#fff",
        color: "#6c757d",
        borderColor: "#6c757d",
    },
    successButton: {
        backgroundColor: "#198754",
        color: "#fff",
        borderColor: "#198754",
    },
    dangerButton: {
        backgroundColor: "#fff",
        color: "#dc3545",
        borderColor: "#dc3545",
    },
    typeCard: {
        border: "1px solid #dee2e6",
        borderRadius: "10px",
        padding: "1.5rem",
        height: "100%",
        cursor: "pointer",
        transition: "all 0.2s ease",
    },
    typeCardActive: {
        borderColor: "#0d6efd",
        boxShadow: "0 5px 15px rgba(13, 110, 253, 0.2)",
        transform: "translateY(-5px)",
    },
    typeCardTitle: {
        fontWeight: "600",
        marginTop: "1rem",
        marginBottom: "0.5rem",
    },
    typeCardTitleActive: {
        color: "#0d6efd",
    },
    typeCardText: {
        color: "#6c757d",
        fontSize: "0.9rem",
        marginBottom: 0,
    },
    radioInput: {
        width: "20px",
        height: "20px",
        margin: "0 auto 1rem auto",
        cursor: "pointer",
    },
    footerButtons: {
        display: "flex",
        justifyContent: "space-between",
        padding: "1.5rem",
        borderTop: "1px solid #e9ecef",
        marginTop: "1rem",
    },
    navButton: {
        display: "flex",
        alignItems: "center",
        gap: "0.5rem",
        padding: "0.75rem 1.5rem",
        borderRadius: "6px",
        fontWeight: "500",
        cursor: "pointer",
    },
    contactCard: {
        marginBottom: "1.5rem",
        border: "1px solid #dee2e6",
        borderRadius: "10px",
        boxShadow: "0 4px 6px rgba(0, 0, 0, 0.04)",
    },
    contactHeader: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: "1rem",
    },
    contactTitle: {
        fontWeight: "600",
        margin: 0,
        color: "#333",
    },
    customFieldRow: {
        display: "flex",
        alignItems: "flex-end",
        marginBottom: "1rem",
    },
    divider: {
        margin: "1.5rem 0",
        borderTop: "1px solid #dee2e6",
    },
    tabsContainer: {
        marginBottom: "2rem",
    },
    tabContent: {
        display: "none",
        padding: "1rem",
    },
    tabContentActive: {
        display: "block",
    },
}