export const typeBankAccountOptions = [
    {value: 0, label: "Selecciona una opción"},
    {value: "Ahorros", label: "Ahorros"},
    {value: "Corriente", label: "Corriente"},
    {value: "Efectivo", label: "Efectivo"},
]

export const bankAccountOptions = [
    {value: 0, label: "Selecciona una opción"},
    {value: 1, label: "Banco Agrario de Colombia"},
    {value: 2, label: "Banco AV Villas"},
    {value: 3, label: "Banco BBVA"},
    {value: 4, label: "Banco Caja Social"},
    {value: 5, label: "Banco Citibank"},
    {value: 6, label: "Banco Davivienda"},
    {value: 7, label: "Banco de Bogotá"},
    {value: 8, label: "Banco de Occidente"},
    {value: 9, label: "Banco Falabella"},
    {value: 10, label: "Banco Finandina"},
    {value: 11, label: "Banco GNB Sudameris"},
    {value: 12, label: "Banco Itaú Corpbanca Colombia S.A."},
    {value: 13, label: "Banco Mundo Mujer"},
    {value: 14, label: "Banco Pichincha"},
    {value: 15, label: "Banco Popular"},
    {value: 16, label: "Banco Credifinanciera"},
    {value: 17, label: "Banco Santander de Negocios Colombia S.A."},
    {value: 18, label: "Bancamia S.A"},
    {value: 19, label: "Banco Serfinanza"},
    {value: 20, label: "Bancoldex"},
    {value: 21, label: "Bancolombia"},
    {value: 22, label: "Bancoomeva"},
    {value: 23, label: "BNP Paribas"},
    {value: 24, label: "Coltefinanciera"},
    {value: 25, label: "Financiera Juriscoop"},
    {value: 26, label: "Banco JP Morgan Colombia"},
    {value: 27, label: "Mibanco S.A"},
    {value: 28, label: "Red Multibanca Colpatria"},
    {value: 29, label: "Simple S.A"},
    {value: 30, label: "Nequi"},
    {value: 31, label: "Daviplata"},
    {value: 32, label: "Efectivo"},
]
